exclude = [".gitignore", ".vscode", "build", "dist"]
target-version = "py313"
line-length = 88
indent-width = 4

[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[lint]
extend-select = ["B"]
